# Generated by Django 6.0.6 on 2026-07-27 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('album', models.CharField(blank=True, max_length=200, null=True)),
                ('duracion', models.IntegerField(blank=True, help_text='Duración en segundos', null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('youtube_video_id', models.CharField(blank=True, max_length=50, null=True)),
                ('portada_url', models.URLField(blank=True, null=True)),
                ('letra', models.TextField(blank=True, null=True)),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'ordering': ['-fecha_agregada'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('es_publica', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.playlist')),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.song')),
            ],
            options={
                'verbose_name': 'Canción en Playlist',
                'verbose_name_plural': 'Canciones en Playlists',
                'ordering': ['orden'],
                'unique_together': {('playlist', 'cancion')},
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='canciones',
            field=models.ManyToManyField(related_name='playlists', through='musica.PlaylistSong', to='musica.song'),
        ),
        migrations.CreateModel(
            name='MusicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen', models.FloatField(default=0.7, help_text='Volumen entre 0 y 1')),
                ('repetir', models.CharField(choices=[('none', 'No repetir'), ('one', 'Repetir una'), ('all', 'Repetir todas')], default='none', max_length=20)),
                ('aleatorio', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_musica', to=settings.AUTH_USER_MODEL)),
                ('ultima_playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musica.playlist')),
                ('ultima_cancion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musica.song')),
            ],
            options={
                'verbose_name': 'Configuración de Música',
                'verbose_name_plural': 'Configuraciones de Música',
            },
        ),
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reproduccion', models.DateTimeField(auto_now_add=True)),
                ('posicion', models.IntegerField(default=0, help_text='Posición en segundos donde se reprodujo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_reproduccion', to=settings.AUTH_USER_MODEL)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproducciones', to='musica.song')),
            ],
            options={
                'verbose_name': 'Historial de Reproducción',
                'verbose_name_plural': 'Historiales de Reproducción',
                'ordering': ['-fecha_reproduccion'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='musica.song')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-fecha_agregada'],
                'unique_together': {('usuario', 'cancion')},
            },
        ),
    ]
