# Generated by Django 4.x
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=300)),
                ('artista', models.CharField(blank=True, db_index=True, default='', max_length=300)),
                ('youtube_id', models.CharField(blank=True, default='', max_length=120)),
                ('letra', models.TextField(blank=True, default='', null=True)),
                ('synced_lyrics', models.TextField(blank=True, default='', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'ordering': ['-actualizado_en'],
                'indexes': [
                    models.Index(fields=['titulo', 'artista'], name='musica_canc_titulo_idx'),
                ],
            },
        ),
    ]
