# Generated by Django 6.0.5 on 2026-05-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cancion',
            new_name='musica_canc_titulo_28d050_idx',
            old_name='musica_canc_titulo_idx',
        ),
    ]
