# Generated by Django 6.0.6 on 2026-06-24 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_original', models.TextField()),
                ('texto_traducido', models.TextField()),
                ('idioma_origen', models.CharField(help_text='Código ISO del idioma de origen (ej: es, en, fr)', max_length=10)),
                ('idioma_destino', models.CharField(help_text='Código ISO del idioma de destino (ej: es, en, fr)', max_length=10)),
                ('idioma_detectado', models.CharField(blank=True, help_text='Idioma detectado automáticamente', max_length=10, null=True)),
                ('fecha_consulta', models.DateTimeField(auto_now=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caché de Traducción',
                'verbose_name_plural': 'Cachés de Traducción',
                'ordering': ['-fecha_consulta'],
                'unique_together': {('texto_original', 'idioma_origen', 'idioma_destino')},
            },
        ),
    ]
