# Generated by Django 6.0.6 on 2026-07-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traductor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranslationCache',
        ),
    ]
