# Generated by Django 6.0.6 on 2026-06-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_perfil_creado_alter_perfil_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='notificaciones_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_publico',
            field=models.BooleanField(default=True),
        ),
    ]
