# Generated by Django 6.0.6 on 2026-06-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_perfil_notificaciones_email_perfil_perfil_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='actividad_en_linea',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='animaciones',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sonidos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tamano_fuente',
            field=models.CharField(choices=[('small', 'Pequeño'), ('normal', 'Normal'), ('large', 'Grande')], default='normal', max_length=10),
        ),
    ]
