# Generated by Django 6.0.6 on 2026-06-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_perfil_actividad_en_linea_perfil_animaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='notificaciones_push',
            field=models.BooleanField(default=False),
        ),
    ]
