# Generated by Django 6.0.6 on 2026-06-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_perfil_notificaciones_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='formato_reloj',
            field=models.CharField(choices=[('12h', '12 horas'), ('24h', '24 horas')], default='24h', max_length=10),
        ),
        migrations.AddField(
            model_name='perfil',
            name='mostrar_fecha',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='mostrar_segundos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='zona_horaria',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
