# Generated by Django 6.0.6 on 2026-07-05 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_perfil_formato_reloj_perfil_mostrar_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='🏆', max_length=50)),
                ('puntos_requeridos', models.IntegerField(default=100)),
                ('tipo', models.CharField(choices=[('chat', 'Chat'), ('musica', 'Música'), ('evento', 'Evento'), ('juego', 'Juego'), ('estudio', 'Estudio'), ('general', 'General')], default='general', max_length=50)),
            ],
            options={
                'verbose_name': 'Logro de Perfil',
                'verbose_name_plural': 'Logros de Perfil',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='color_acento',
            field=models.CharField(choices=[('purple', 'Púrpura'), ('blue', 'Azul'), ('green', 'Verde'), ('orange', 'Naranja'), ('red', 'Rojo')], default='purple', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='experiencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='experiencia_siguiente_nivel',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ciudad, País', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tema',
            field=models.CharField(choices=[('dark', 'Oscuro'), ('light', 'Claro'), ('auto', 'Automático')], default='dark', max_length=10),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('chat', 'Chat IA'), ('musica', 'Música'), ('evento', 'Evento'), ('juego', 'Juego'), ('estudio', 'Estudio'), ('traduccion', 'Traducción'), ('blog', 'Blog')], max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad de Usuario',
                'verbose_name_plural': 'Actividades de Usuarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='UserProfileAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueado', models.DateTimeField(auto_now_add=True)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.profileachievement')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logro Desbloqueado',
                'verbose_name_plural': 'Logros Desbloqueados',
                'ordering': ['-fecha_desbloqueado'],
                'unique_together': {('usuario', 'logro')},
            },
        ),
    ]
