# Generated by Django 6.0.6 on 2026-07-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_profileachievement_perfil_color_acento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='aprender_habitos_ia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='compartir_estadisticas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='guardar_historial_ia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='mostrar_ultima_conexion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='recomendaciones_ia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='recordar_preferencias_ia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sugerencias_ia',
            field=models.BooleanField(default=True),
        ),
    ]
