# Generated by Django 6.0.6 on 2026-07-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_perfil_aprender_habitos_ia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nombre_amigis',
            field=models.CharField(blank=True, default='Amigis', help_text='Nombre personalizado para tu mascota patito', max_length=50),
        ),
    ]
