# Generated by Django 6.0.6 on 2026-07-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_perfil_nombre_amigis'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='patito_accesorio',
            field=models.CharField(choices=[('none', 'Ninguno'), ('glasses', 'Gafas'), ('hat', 'Gorra'), ('bow', 'Lazo')], default='none', help_text='Accesorio del patito', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='patito_color_cuerpo',
            field=models.CharField(choices=[('yellow', 'Amarillo'), ('orange', 'Naranja'), ('white', 'Blanco'), ('pink', 'Rosa')], default='yellow', help_text='Color del cuerpo del patito', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='patito_color_ropa',
            field=models.CharField(choices=[('purple', 'Morada'), ('blue', 'Azul'), ('green', 'Verde'), ('red', 'Roja'), ('black', 'Negra'), ('white', 'Blanca')], default='purple', help_text='Color de la ropa', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='patito_estilo',
            field=models.CharField(choices=[('normal', 'Normal'), ('neon', 'Neón'), ('gradient', 'Gradiente')], default='normal', help_text='Estilo visual del patito', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='patito_ropa',
            field=models.CharField(choices=[('hoodie', 'Sudadera'), ('shirt', 'Camiseta'), ('none', 'Sin ropa')], default='hoodie', help_text='Tipo de ropa del patito', max_length=20),
        ),
    ]
