# Generated by Django 6.0.6 on 2026-06-24 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugerencias', '0002_sugerencia_fecha_respuesta_sugerencia_respondido_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_primera_interaccion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_interaccion', models.DateTimeField(auto_now=True)),
                ('total_sugerencias', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'ordering': ['-fecha_ultima_interaccion'],
            },
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias', to='sugerencias.visitante'),
        ),
    ]
