# Generated by Django 6.0.6 on 2026-07-27 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEntretenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('icono', models.CharField(default='🎬', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría de Entretenimiento',
                'verbose_name_plural': 'Categorías de Entretenimiento',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ContenidoEntretenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pelicula', 'Película'), ('serie', 'Serie'), ('anime', 'Anime'), ('libro', 'Libro'), ('manga', 'Manga'), ('musica', 'Música'), ('podcast', 'Podcast'), ('radio', 'Radio'), ('meme', 'Meme'), ('fondo', 'Fondo de Pantalla'), ('curiosidad', 'Curiosidad'), ('juego', 'Juego Recomendado')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('genero', models.CharField(blank=True, max_length=100)),
                ('imagen', models.URLField(blank=True, help_text='URL de la imagen del póster/portada')),
                ('anio', models.IntegerField(blank=True, help_text='Año de lanzamiento', null=True)),
                ('duracion', models.CharField(blank=True, help_text='Duración o extensión', max_length=50)),
                ('calificacion', models.DecimalField(decimal_places=1, default=0.0, help_text='Calificación de 0 a 10', max_digits=3)),
                ('director', models.CharField(blank=True, help_text='Director, autor o creador', max_length=255)),
                ('plataforma', models.CharField(blank=True, help_text='Plataforma donde ver/escuchar', max_length=100)),
                ('es_destacado', models.BooleanField(default=False, help_text='Marcar como recomendación del día')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entretenimiento.categoriaentretenimiento')),
            ],
            options={
                'verbose_name': 'Contenido de Entretenimiento',
                'verbose_name_plural': 'Contenidos de Entretenimiento',
                'ordering': ['-es_destacado', '-calificacion', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RecomendacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.TextField(help_text='Razón de la recomendación por IA')),
                ('fecha_recomendacion', models.DateTimeField(auto_now_add=True)),
                ('vista', models.BooleanField(default=False)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entretenimiento.contenidoentretenimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recomendación IA',
                'verbose_name_plural': 'Recomendaciones IA',
                'ordering': ['-fecha_recomendacion'],
            },
        ),
        migrations.CreateModel(
            name='FavoritoEntretenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entretenimiento.contenidoentretenimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito de Entretenimiento',
                'verbose_name_plural': 'Favoritos de Entretenimiento',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('usuario', 'contenido')},
            },
        ),
    ]
