# Generated by Django 6.0.6 on 2026-07-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidoentretenimiento',
            name='trailer',
            field=models.URLField(blank=True, help_text='URL del tráiler en YouTube'),
        ),
        migrations.AlterField(
            model_name='contenidoentretenimiento',
            name='tipo',
            field=models.CharField(choices=[('pelicula', 'Película'), ('serie', 'Serie'), ('anime', 'Anime'), ('libro', 'Libro'), ('manga', 'Manga'), ('musica', 'Música'), ('podcast', 'Podcast'), ('documental', 'Documental'), ('teatro', 'Teatro'), ('radio', 'Radio'), ('meme', 'Meme'), ('fondo', 'Fondo de Pantalla'), ('curiosidad', 'Curiosidad'), ('juego', 'Juego Recomendado')], max_length=20),
        ),
    ]
