# Generated by Django 6.0.6 on 2026-07-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fijada', '-prioridad', '-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='notificacion',
            name='categoria',
            field=models.CharField(choices=[('chat_ia', 'Chat IA'), ('musica', 'Música'), ('estudio', 'Estudio'), ('evento', 'Eventos'), ('soporte', 'Soporte'), ('sistema', 'Sistema'), ('clima', 'Clima'), ('traductor', 'Traductor'), ('juegos', 'Juegos')], default='sistema', max_length=50),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fijada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('normal', 'Normal'), ('baja', 'Baja')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('error', 'Error'), ('evento', 'Evento'), ('chat_ia', 'Chat IA'), ('musica', 'Música'), ('estudio', 'Estudio'), ('soporte', 'Soporte'), ('sistema', 'Sistema')], default='info', max_length=50),
        ),
    ]
