# Generated by Django 6.0.6 on 2026-06-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='notificacion_1dia_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='notificacion_1hora_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
