# Generated by Django 6.0.6 on 2026-07-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_evento_options_evento_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('personal', '🎂 Personal'), ('trabajo', '💼 Trabajo'), ('estudios', '📚 Estudios'), ('salud', '🏥 Salud'), ('fiesta', '🎉 Fiesta'), ('otro', '📌 Otro')], default='personal', help_text='Categoría del evento', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='recordatorio_activo',
            field=models.BooleanField(default=True, help_text='Activar recordatorio'),
        ),
        migrations.AddField(
            model_name='evento',
            name='recordatorio_minutos_antes',
            field=models.IntegerField(default=30, help_text='Minutos antes del evento para el recordatorio'),
        ),
        migrations.AddField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ubicación del evento', max_length=200, null=True),
        ),
    ]
