# Generated by Django 6.0.3 on 2026-03-31 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0004_alter_message_options_remove_message_recipient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledmessage',
            options={'ordering': ['-programado_para']},
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='default.png', upload_to='perfiles/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='tipo',
            field=models.CharField(choices=[('checkin', 'Check-in'), ('motivacional', 'Motivacional'), ('historial', 'Historial'), ('saludo', 'Saludo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_programados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuario_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuario_permissions', to='auth.permission'),
        ),
    ]
