# Generated by Django 6.0.3 on 2026-04-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_evento_options_alter_evento_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='veces_recordado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evento',
            name='veces_recordado_dia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('user', 'Usuario'), ('bot', 'Bot'), ('event_notification', 'Notificación de evento')], default='user', max_length=20),
        ),
    ]
