# Generated by Django 6.0.3 on 2026-04-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_evento_veces_recordado_evento_veces_recordado_dia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='scheduledmessage',
            options={'ordering': ['-programado_para'], 'verbose_name': 'Mensaje programado', 'verbose_name_plural': 'Mensajes programados'},
        ),
        migrations.AlterField(
            model_name='evento',
            name='veces_recordado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evento',
            name='veces_recordado_dia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='perfiles/default.png', upload_to='perfiles/'),
        ),
    ]
