# Generated by Django 6.0.3 on 2026-04-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_message_options_alter_scheduledmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('general', '📌 General'), ('trabajo', '💼 Trabajo'), ('salud', '💊 Salud'), ('social', '🎉 Social'), ('cumple', '🎂 Cumpleaños'), ('viaje', '✈️ Viaje'), ('otro', '🔖 Otro')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='color',
            field=models.CharField(default='#e91e63', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='recordatorio_1_dia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='recordatorio_5_dias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='recordatorio_hoy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bot_nombre',
            field=models.CharField(default='MiniAmigixV', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fondo_tipo',
            field=models.CharField(default='gradient', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fondo_valor',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fuente_chat',
            field=models.CharField(default='DM Sans', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='musica_activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='racha_dias',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_visita',
            field=models.DateField(blank=True, null=True),
        ),
    ]
