# Generated by Django 6.0.4 on 2026-04-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_blog_cancion_entretenimiento_estudio_noticia_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='youtube_url',
            field=models.CharField(help_text='Enlace de YouTube', max_length=1000),
        ),
    ]
