# Generated by Django 6.0.4 on 2026-04-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_cancion_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(default='Quito', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='clima_cache',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
