# Generated by Django 6.0.4 on 2026-05-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_conversation_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='icon',
            field=models.CharField(default='💬', max_length=10),
        ),
    ]
