# Generated by Django 5.1.15 on 2026-06-13 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsoporte',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketsoporte',
            name='respondido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_respondidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketsoporte',
            name='respuesta_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
