# Generated by Django 6.0.6 on 2026-07-27 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('clasico', 'Clásico'), ('ia', 'Juego con IA'), ('educativo', 'Educativo'), ('arcade', 'Arcade')], max_length=50)),
                ('icono', models.CharField(default='🎮', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='🏅', max_length=50)),
                ('puntos_xp', models.IntegerField(default=0, help_text='Puntos de experiencia otorgados')),
                ('condicion', models.JSONField(default=dict, help_text='Condiciones para desbloquear el logro')),
                ('activo', models.BooleanField(default=True)),
                ('juego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='juegos.game')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'ordering': ['puntos_xp', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('puntuacion_final', models.IntegerField(blank=True, null=True)),
                ('nivel_alcanzado', models.IntegerField(default=1)),
                ('gano', models.BooleanField(blank=True, null=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='juegos.game')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_juego', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Juego',
                'verbose_name_plural': 'Sesiones de Juego',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_puntos_xp', models.IntegerField(default=0)),
                ('total_monedas', models.IntegerField(default=0)),
                ('juegos_completados', models.IntegerField(default=0)),
                ('racha_dias', models.IntegerField(default=0)),
                ('ultima_jugada', models.DateField(blank=True, null=True)),
                ('nivel', models.IntegerField(default=1)),
                ('insignia', models.CharField(default='Novato', max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_juegos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadísticas de Usuario',
                'verbose_name_plural': 'Estadísticas de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('nivel', models.IntegerField(default=1)),
                ('tiempo_jugado', models.IntegerField(default=0, help_text='Tiempo en segundos')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones', to='juegos.game')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Puntuación',
                'verbose_name_plural': 'Puntuaciones',
                'ordering': ['-puntuacion', '-fecha'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'juego', 'fecha'), name='unique_user_game_date')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueo', models.DateTimeField(auto_now_add=True)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_desbloqueados', to='juegos.achievement')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros_desbloqueados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logro de Usuario',
                'verbose_name_plural': 'Logros de Usuarios',
                'ordering': ['-fecha_desbloqueo'],
                'unique_together': {('usuario', 'logro')},
            },
        ),
    ]
