# Generated by Django 6.0.6 on 2026-06-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0001_initial'),
    ]

    operations = [
    ]
