# Generated by Django 6.0.6 on 2026-06-21 03:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0002_auto_20260617_2140'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('icono', models.CharField(default='📚', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Estudio',
                'verbose_name_plural': 'Categorías de Estudio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='StudyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('contenido', models.TextField()),
                ('tipo_recurso', models.CharField(choices=[('nota', 'Nota'), ('resumen', 'Resumen'), ('guia', 'Guía'), ('ejercicio', 'Ejercicio'), ('video', 'Video'), ('enlace', 'Enlace')], default='nota', max_length=50)),
                ('etiquetas', models.CharField(blank=True, help_text='Etiquetas separadas por comas', max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('es_publico', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='estudio.studycategory')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurso de Estudio',
                'verbose_name_plural': 'Recursos de Estudio',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='StudyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_completado', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('notas_usuario', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_estudio', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso', to='estudio.studyresource')),
            ],
            options={
                'verbose_name': 'Progreso de Estudio',
                'verbose_name_plural': 'Progresos de Estudio',
                'ordering': ['-ultima_actividad'],
                'unique_together': {('usuario', 'recurso')},
            },
        ),
    ]
