# Generated by Django 6.0.6 on 2026-07-05 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0003_studycategory_studyresource_studyprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_minutos', models.IntegerField(default=25)),
                ('completado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('trabajo', 'Trabajo'), ('descanso_corto', 'Descanso Corto'), ('descanso_largo', 'Descanso Largo')], default='trabajo', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión Pomodoro',
                'verbose_name_plural': 'Sesiones Pomodoro',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_segundos', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tipo_sesion', models.CharField(choices=[('cronometro', 'Cronómetro'), ('pomodoro', 'Pomodoro'), ('temporizador', 'Temporizador')], default='cronometro', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_estudio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Estudio',
                'verbose_name_plural': 'Sesiones de Estudio',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('tiempo_estudiado_segundos', models.IntegerField(default=0)),
                ('pomodoros_completados', models.IntegerField(default=0)),
                ('notas_creadas', models.IntegerField(default=0)),
                ('resumenes_creados', models.IntegerField(default=0)),
                ('racha_dias', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_diarias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadística Diaria',
                'verbose_name_plural': 'Estadísticas Diarias',
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]
