# Generated by Django 6.0.6 on 2026-07-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0004_pomodorosession_studysession_dailystats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-fijada', '-fecha_creacion'], 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AddField(
            model_name='nota',
            name='color',
            field=models.CharField(default='#fef08a', help_text='Color de la nota en formato HEX', max_length=7),
        ),
        migrations.AddField(
            model_name='nota',
            name='fijada',
            field=models.BooleanField(default=False, help_text='Si la nota está fijada arriba'),
        ),
    ]
