# Generated by Django 6.0.6 on 2026-08-10 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0005_alter_nota_options_nota_color_nota_fijada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='🎁', max_length=50)),
                ('categoria', models.CharField(choices=[('ropa', '👕 Ropa'), ('accesorios', '🎮 Accesorios'), ('decoracion', '🏠 Decoración'), ('especial', '✨ Especial')], max_length=20)),
                ('precio', models.IntegerField(default=50)),
                ('xp_requerido', models.IntegerField(default=0, help_text='XP mínimo requerido para comprar')),
                ('limitado', models.BooleanField(default=False, help_text='Si es un artículo limitado')),
                ('stock', models.IntegerField(default=0, help_text='Stock disponible si es limitado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Accesorio',
                'verbose_name_plural': 'Accesorios',
                'ordering': ['precio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='🏆', max_length=50)),
                ('xp_requerido', models.IntegerField(default=0)),
                ('misiones_requeridas', models.IntegerField(default=0)),
                ('condicion_especial', models.TextField(blank=True, help_text='Condición especial para obtener la insignia', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insignia',
                'verbose_name_plural': 'Insignias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LeccionRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('pregunta', models.CharField(max_length=300)),
                ('contenido', models.TextField(help_text='Contenido educativo breve')),
                ('tiempo_estimado_minutos', models.IntegerField(default=5)),
                ('categoria', models.CharField(default='general', max_length=50)),
                ('xp_recompensa', models.IntegerField(default=30)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lección Rápida',
                'verbose_name_plural': 'Lecciones Rápidas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('curiosidad', '🧠 Algo curioso'), ('vida', '💰 Algo para mi vida'), ('practico', '🍳 Algo práctico'), ('creativo', '🎨 Algo creativo'), ('mundo', '🌎 Algo del mundo'), ('habilidades', '🗣️ Algo para mejorar mis habilidades'), ('sorprendeme', '🎲 Sorpréndeme')], max_length=20)),
                ('xp_recompensa', models.IntegerField(default=50)),
                ('monedas_recompensa', models.IntegerField(default=20)),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='facil', max_length=20)),
                ('contenido_interactivo', models.JSONField(default=dict, help_text='Contenido de la misión en formato JSON')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Misión Amigis',
                'verbose_name_plural': 'Misiones Amigis',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0, help_text='Puntos de experiencia')),
                ('nivel', models.IntegerField(default=1, help_text='Nivel actual del usuario')),
                ('monedas', models.IntegerField(default=100, help_text='Monedas Amigis')),
                ('racha_actual', models.IntegerField(default=0, help_text='Días consecutivos de actividad')),
                ('racha_maxima', models.IntegerField(default=0, help_text='Racha máxima histórica')),
                ('misiones_completadas', models.IntegerField(default=0, help_text='Total de misiones completadas')),
                ('fecha_ultima_actividad', models.DateField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_amigis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Amigis',
                'verbose_name_plural': 'Perfiles Amigis',
            },
        ),
        migrations.CreateModel(
            name='AccesorioUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('equipado', models.BooleanField(default=False)),
                ('accesorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietarios', to='estudio.accesorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesorios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accesorio de Usuario',
                'verbose_name_plural': 'Accesorios de Usuarios',
                'ordering': ['-fecha_compra'],
                'unique_together': {('usuario', 'accesorio')},
            },
        ),
        migrations.CreateModel(
            name='InsigniaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateTimeField(auto_now_add=True)),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganadores', to='estudio.insignia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insignia de Usuario',
                'verbose_name_plural': 'Insignias de Usuarios',
                'ordering': ['-fecha_obtenida'],
                'unique_together': {('usuario', 'insignia')},
            },
        ),
        migrations.CreateModel(
            name='MisionCompletada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completacion', models.DateTimeField(auto_now_add=True)),
                ('xp_ganado', models.IntegerField()),
                ('monedas_ganadas', models.IntegerField()),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completaciones', to='estudio.mision')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misiones_completadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Misión Completada',
                'verbose_name_plural': 'Misiones Completadas',
                'ordering': ['-fecha_completacion'],
                'unique_together': {('usuario', 'mision')},
            },
        ),
    ]
