# Generated by Django 6.0.6 on 2026-08-10 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0006_accesorio_insignia_leccionrapida_mision_userprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='titulo',
            field=models.CharField(blank=True, default='', help_text='Título de la nota', max_length=200),
        ),
        migrations.CreateModel(
            name='MetaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_diarias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta Diaria',
                'verbose_name_plural': 'Metas Diarias',
                'ordering': ['orden', '-fecha'],
                'unique_together': {('usuario', 'titulo', 'fecha')},
            },
        ),
    ]
