# Generated by Django 6.0.6 on 2026-07-15 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bandera de Característica',
                'verbose_name_plural': 'Banderas de Características',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('email_host', models.CharField(blank=True, max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.EmailField(blank=True, max_length=254)),
                ('email_host_password', models.CharField(blank=True, max_length=255)),
                ('push_api_key', models.CharField(blank=True, max_length=255)),
                ('sms_api_key', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_login_attempts', models.IntegerField(default=5, help_text='Intentos máximos de login')),
                ('lockout_duration', models.IntegerField(default=30, help_text='Duración de bloqueo en minutos')),
                ('password_min_length', models.IntegerField(default=8, help_text='Longitud mínima de contraseña')),
                ('password_require_uppercase', models.BooleanField(default=True)),
                ('password_require_lowercase', models.BooleanField(default=True)),
                ('password_require_numbers', models.BooleanField(default=True)),
                ('password_require_special', models.BooleanField(default=True)),
                ('session_timeout', models.IntegerField(default=60, help_text='Tiempo de sesión en minutos')),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('ip_whitelist', models.TextField(blank=True, help_text='Lista blanca de IPs (una por línea)')),
                ('ip_blacklist', models.TextField(blank=True, help_text='Lista negra de IPs (una por línea)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Seguridad',
                'verbose_name_plural': 'Configuraciones de Seguridad',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MiniAmigixV', max_length=100)),
                ('site_description', models.TextField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Activar modo mantenimiento')),
                ('maintenance_message', models.TextField(blank=True, help_text='Mensaje mostrado durante mantenimiento')),
                ('allow_registration', models.BooleanField(default=True, help_text='Permitir nuevos registros')),
                ('max_users', models.IntegerField(blank=True, help_text='Límite de usuarios (null = sin límite)', null=True)),
                ('default_theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro')], default='dark', max_length=20)),
                ('default_language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('primary_color', models.CharField(default='#6366f1', help_text='Color primario en HEX', max_length=7)),
                ('secondary_color', models.CharField(default='#8b5cf6', help_text='Color secundario en HEX', max_length=7)),
                ('background_color', models.CharField(default='#0f172a', help_text='Color de fondo en HEX', max_length=7)),
                ('text_color', models.CharField(default='#f8fafc', help_text='Color de texto en HEX', max_length=7)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Tema',
                'verbose_name_plural': 'Configuraciones de Temas',
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Cambio de Contraseña'), ('profile_update', 'Actualización de Perfil'), ('settings_change', 'Cambio de Configuración'), ('api_access', 'Acceso a API'), ('file_upload', 'Subida de Archivo'), ('file_download', 'Descarga de Archivo')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='configuraci_user_id_f0f0f0_idx'), models.Index(fields=['action', '-timestamp'], name='configuraci_action_0df1ad_idx')],
            },
        ),
    ]
