# Generated by Django 6.0.5 on 2026-05-26 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='profile_pics/default.png', upload_to='profile_pics/')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('ai_name', models.CharField(default='Asistente IA', max_length=50)),
                ('profile_background', models.CharField(default='default', max_length=200)),
                ('app_background', models.CharField(default='default', max_length=200)),
                ('screen_appearance', models.CharField(default='standard', max_length=50)),
                ('theme_preference', models.CharField(default='dark', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
