# Generated by Django 6.0.5 on 2026-05-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_supportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='tipo',
            field=models.CharField(choices=[('ayuda', 'Ayuda'), ('consulta', 'Consulta'), ('sugerencia', 'Sugerencia'), ('problema', 'Problema Técnico'), ('solicitud', 'Solicitud de Funcionalidad'), ('reporte', 'Reporte de Error'), ('informacion', 'Solicitud de Información')], default='consulta', max_length=20),
        ),
    ]
