# ============================================================================
# DJANGO SETTINGS FOR MINIAMIGIXV
# ============================================================================

"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# ============================================================================
# IMPORTS
# ============================================================================

import os
import sys
from datetime import timedelta
from importlib.util import find_spec
from pathlib import Path
from dotenv import load_dotenv

# ============================================================================
# BASIC CONFIGURATION
# ============================================================================

# Load environment variables from .env file
load_dotenv(os.path.join(Path(__file__).resolve().parent.parent, '.env'), override=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add project root to Python path for imports
sys.path.insert(0, str(BASE_DIR))

# Optional dependencies
HAS_DJANGO_RATELIMIT = find_spec('django_ratelimit') is not None
HAS_CORSHEADERS = find_spec('corsheaders') is not None

# ============================================================================
# SECURITY SETTINGS
# ============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-default-dev-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,10.19.45.68').split(',')

# Agregar URL de ngrok si no está presente
if 'yasmin-uncalumniative-demetria.ngrok-free.dev' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('yasmin-uncalumniative-demetria.ngrok-free.dev')

# URL base del sitio para correos electrónicos y enlaces absolutos
SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000')

# Configuración para túneles (ngrok) y HTTPS
CSRF_TRUSTED_ORIGINS = [
    'https://yasmin-uncalumniative-demetria.ngrok-free.dev',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://127.0.0.1:50769',
    'http://10.19.45.68:8000',
]

# Configuración CORS (solo en desarrollo)
if DEBUG:
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:5173',
        'http://127.0.0.1:5173',
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'http://10.19.45.68:8000',
    ]
    CORS_ALLOW_CREDENTIALS = True
else:
    # En producción, configurar orígenes específicos
    CORS_ALLOWED_ORIGINS = [o for o in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if o]
    CORS_ALLOW_CREDENTIALS = True

# Para que Django reconozca que está detrás de un proxy con HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ============================================================================
# APPLICATION CONFIGURATION
# ============================================================================

INSTALLED_APPS = [
    # Django Core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required by allauth
    
    # Allauth (Authentication)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.microsoft',
    
    # Temporalmente deshabilitado - requiere instalación de MongoDB
    # 'mongoengine',
    # 'mongodb',
    
    # Project Apps (Alphabetical Order)
    'apps.api',
    'apps.app.apps.AppConfig',
    'apps.blog.apps.BlogConfig',
    'apps.clima',
    'apps.configuracion',
    'apps.entretenimiento',
    'apps.estudio',
    'apps.eventos',
    'apps.juegos.apps.JuegosConfig',
    'apps.musica.apps.MusicaConfig',
    'apps.notificaciones',
    'apps.perfil',
    'apps.soporte',
    'apps.sugerencias',
    'apps.traductor',
    'apps.tutorial',
    
    # REST Framework
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
]

# Optional apps
if HAS_DJANGO_RATELIMIT:
    INSTALLED_APPS.append('django_ratelimit')

if HAS_CORSHEADERS:
    INSTALLED_APPS.append('corsheaders')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.app.middleware.SecurityHeadersMiddleware',
    'apps.app.middleware.XSSProtectionMiddleware',
]

if HAS_CORSHEADERS:
    MIDDLEWARE.insert(1, 'corsheaders.middleware.CorsMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.notificaciones.context_processors.notificaciones_sin_leer',
                'apps.perfil.context_processors.perfil_settings',
                'config.context_processors.site_url',
                'config.context_processors.user_theme',
                'config.context_processors.is_admin_user',
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ] if DEBUG else [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# ============================================================================
# DATABASE CONFIGURATION
# ============================================================================

# SQLite (Base de datos principal - Desarrollo)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
}

# PostgreSQL (Producción - descomentar cuando esté configurado)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('POSTGRES_DB', 'miniamigixv_db'),
#         'USER': os.getenv('POSTGRES_USER', 'postgres'),
#         'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),
#         'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
#         'PORT': os.getenv('POSTGRES_PORT', '5432'),
#     },
# }

# MongoDB Configuration (deshabilitado - requiere instalación de MongoDB)
# MONGO_APPS = [
#     'notificaciones',
#     'chats',
#     'recomendaciones',
#     'analitica',
#     'juegos_data'
# ]
# DATABASE_ROUTERS = ['config.db_router.DatabaseRouter']

# ============================================================================
# AUTHENTICATION CONFIGURATION (ALLAUTH)
# ============================================================================

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*']
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_UNIQUE_EMAIL = True

ACCOUNT_EMAIL_SUBJECT_PREFIX = ''
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http'
ACCOUNT_ADAPTER = 'apps.app.adapters.AccountAdapter'

# Social Account Configuration
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_ADAPTER = 'apps.app.adapters.SocialAccountAdapter'
SOCIALACCOUNT_LOGIN_ON_GET = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'OAUTH2_PKCE_ENABLED': False,
        'VERIFIED_EMAIL': True,
        'AUTH_PARAMS': {
            'prompt': 'select_account',
        },
    },
    'github': {
        # Configuration via Django admin (SocialApp model)
    },
    'microsoft': {
        # Configuration via Django admin (SocialApp model)
    }
}

# ============================================================================
# PASSWORD VALIDATION
# ============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================================================================
# INTERNATIONALIZATION
# ============================================================================

LANGUAGE_CODE = 'es'

LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
]

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True

# ============================================================================
# STATIC & MEDIA FILES
# ============================================================================

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_PERMISSIONS = 0o644

# ============================================================================
# API KEYS CONFIGURATION
# ============================================================================

# AI APIs
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GOOGLE_API_KEY = os.getenv("GEMINI_API_KEY")
GOOGLE_CLOUD_VISION_API_KEY = os.getenv("GOOGLE_CLOUD_VISION_API_KEY")
OLLAMA_API_URL = os.getenv("OLLAMA_API_URL", "http://localhost:11434")
if OLLAMA_API_URL and not OLLAMA_API_URL.endswith('/v1') and not OLLAMA_API_URL.endswith('/v1/'):
    OLLAMA_API_URL = OLLAMA_API_URL.rstrip('/') + '/v1'
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3.3")

# External APIs
OPENWEATHER_API_KEY = os.getenv("OPENWEATHER_API_KEY")
WEATHERAPI_KEY = os.getenv("WEATHERAPI_KEY")
YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY")

# ============================================================================
# EMAIL CONFIGURATION
# ============================================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'miniamigixv@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Admin emails
ADMIN_EMAILS = ['miniamigixv@gmail.com', 'mariajosetacoc2005@gmail.com']

# Login/Logout redirects
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
ACCOUNT_LOGOUT_REDIRECT_URL = 'home'

# ============================================================================
# WEBPUSH CONFIGURATION (TEMPORARILY DISABLED)
# ============================================================================

# Reemplaza con las claves generadas por 'python manage.py webpush_generate_vapid_key'
WEBPUSH_VAPID_PRIVATE_KEY = os.getenv('WEBPUSH_VAPID_PRIVATE_KEY', 'TU_CLAVE_PRIVADA_AQUI')
WEBPUSH_VAPID_PUBLIC_KEY = os.getenv('WEBPUSH_VAPID_PUBLIC_KEY', 'TU_CLAVE_PUBLICA_AQUI')
WEBPUSH_CONTACT_EMAIL = os.getenv('WEBPUSH_CONTACT_EMAIL', 'tu_email@ejemplo.com')

# ============================================================================
# REST FRAMEWORK CONFIGURATION
# ============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/min',
        'user': '100/min'
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}

# Rate limiting
RATELIMIT_ENABLE = True
RATELIMIT_VIEW = 'rest_framework.throttling.AnonRateThrottle'

# drf-spectacular configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'MiniAmigixV API',
    'DESCRIPTION': 'API REST para la plataforma MiniAmigixV',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# ============================================================================
# MONGODB CONFIGURATION (TEMPORARILY DISABLED)
# ============================================================================

MONGODB_URI = os.getenv('MONGODB_URI', 'mongodb://localhost:27017/')
MONGODB_NAME = os.getenv('MONGODB_NAME', 'miniamigixv_db')
MONGOENGINE_USER_DOCUMENT = 'mongoengine.django.auth.User'

# Conectar a MongoDB (deshabilitado temporalmente - requiere instalación)
# try:
#     from mongoengine import connect
#     connect(db=MONGODB_NAME, host=MONGODB_URI, alias='default')
#     print(f"[OK] Conectado a MongoDB: {MONGODB_NAME}")
# except ImportError:
#     print("[WARN] mongoengine no esta instalado. MongoDB no estara disponible.")
# except Exception as e:
#     print(f"[ERROR] Error al conectar a MongoDB: {str(e)}")

# ============================================================================
# CACHE CONFIGURATION
# ============================================================================

# DummyCache para desarrollo (compatible con django_ratelimit)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}

SILENCED_SYSTEM_CHECKS = [
    'django_ratelimit.W001',  # DummyCache no es oficialmente soportado pero funciona en desarrollo
    'django_ratelimit.E003',  # Silenciar error de shared cache en desarrollo
]

# Redis (Memurai) - Caching y sesiones (deshabilitado - requiere instalación)
# REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
# REDIS_PORT = os.getenv('REDIS_PORT', '6379')
# REDIS_DB = os.getenv('REDIS_DB', '0')
# REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', None)
#
# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': f'redis://{":" + REDIS_PASSWORD + "@" if REDIS_PASSWORD else ""}{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#             'CONNECTION_POOL_KWARGS': {
#                 'max_connections': 50,
#                 'retry_on_timeout': True,
#             }
#         },
#         'KEY_PREFIX': 'miniamigixv',
#         'TIMEOUT': 300,  # 5 minutos por defecto
#     }
# }

# Session configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Session configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# ============================================================================
# SECURITY CONFIGURATION
# ============================================================================

# Cookie configuration
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'

# Development security settings
SECURE_SSL_REDIRECT = False
SECURE_HSTS_SECONDS = 0

# Production security settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ============================================================================
# TEMPLATE LOADERS
# ============================================================================

if DEBUG:
    TEMPLATE_LOADERS = [
        'django.template.loaders.filesystem.Loader',
        'django.template.loaders.app_directories.Loader',
    ]
else:
    TEMPLATE_LOADERS = [
        ('django.template.loaders.cached.Loader', [
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
        ]),
    ]
