"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv(os.path.join(Path(__file__).resolve().parent.parent, '.env'), override=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add apps directory to Python path
sys.path.insert(0, str(BASE_DIR / 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-default-dev-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# URL base del sitio para correos electrónicos y enlaces absolutos
SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000')

# Configuración para túneles (ngrok) y HTTPS
CSRF_TRUSTED_ORIGINS = [
    'https://yasmin-uncalumniative-demetria.ngrok-free.dev',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://127.0.0.1:50769',
]

# Para que Django reconozca que está detrás de un proxy con HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Allauth apps
    'django.contrib.sites', # Required by allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    # 'webpush', # Temporalmente deshabilitado - incompatible con Django 6.0
    # MongoEngine
    'mongoengine',
    # MongoDB App
    'mongodb',
    # Project Apps
    'app.apps.AppConfig',
    'configuracion',
    'eventos',
    'notificaciones',
    'perfil',
    'sugerencias',
    'soporte',
    'tutorial',
    'estudio',
    'clima',
    'traductor',
    'rest_framework',
    'rest_framework_simplejwt',
    'apps.api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware', # Allauth middleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notificaciones.context_processors.notificaciones_sin_leer',
                'perfil.context_processors.perfil_settings',
                'config.context_processors.site_url',
                'config.context_processors.user_theme',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Aplicaciones que usarán MongoDB (deshabilitado temporalmente)
# MONGO_APPS = [
#     'notificaciones',
#     'chats', 
#     'recomendaciones',
#     'analitica',
#     'juegos_data'
# ]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    # 'mongodb': {
    #     'ENGINE': 'djongo',
    #     'NAME': os.getenv('MONGODB_NAME', 'miniamigixv_db'),
    #     'ENFORCE_SCHEMA': False,
    #     'CLIENT': {
    #         'host': os.getenv('MONGODB_URI', 'mongodb://localhost:27017/'),
    #     }
    # }
}

# DATABASE_ROUTERS = ['config.db_router.DatabaseRouter']

# Allauth specific settings
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', # Default Django authentication
    'allauth.account.auth_backends.AuthenticationBackend', # allauth specific authentication
]

SITE_ID = 1 # Required by allauth

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*']
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_UNIQUE_EMAIL = True

# Configuración de email para allauth
ACCOUNT_EMAIL_SUBJECT_PREFIX = ''
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http'  # Cambiar a 'https' en producción
ACCOUNT_ADAPTER = 'apps.app.adapters.AccountAdapter'

# Auto-signup para redes sociales (evitar formulario adicional)
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

# Adaptador personalizado para generar username automáticamente
SOCIALACCOUNT_ADAPTER = 'apps.app.adapters.SocialAccountAdapter'

# Saltar la página de confirmación de inicio de sesión social ("Continuar")
SOCIALACCOUNT_LOGIN_ON_GET = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'OAUTH2_PKCE_ENABLED': False,
        'VERIFIED_EMAIL': True,
        'AUTH_PARAMS': {
            'prompt': 'select_account',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Avatars)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_PERMISSIONS = 0o644

# Configuración de APIs de IA
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GOOGLE_API_KEY = os.getenv("GEMINI_API_KEY")
OPENWEATHER_API_KEY = os.getenv("OPENWEATHER_API_KEY")
YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY")
OLLAMA_API_URL = os.getenv("OLLAMA_API_URL", "http://localhost:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3.3")

# Configuración de Email para Sugerencias
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True # Consider EMAIL_USE_SSL = True if using port 465
EMAIL_HOST_USER = 'miniamigixv@gmail.com'
EMAIL_HOST_PASSWORD = "ineiftsmayttlflr"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# Lista de correos con permisos de administrador
ADMIN_EMAILS = ['miniamigixv@gmail.com']

# Configuración de redirección de Login
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home' # Redirige a 'home' después de un login exitoso
ACCOUNT_LOGOUT_REDIRECT_URL = 'home' # Redirige a 'home' después de un logout

# Configuración de WebPush (VAPID keys)
# Reemplaza con las claves generadas por 'python manage.py webpush_generate_vapid_key'
# y tu correo electrónico de contacto.
WEBPUSH_VAPID_PRIVATE_KEY = os.getenv('WEBPUSH_VAPID_PRIVATE_KEY', 'TU_CLAVE_PRIVADA_AQUI')
WEBPUSH_VAPID_PUBLIC_KEY = os.getenv('WEBPUSH_VAPID_PUBLIC_KEY', 'TU_CLAVE_PUBLICA_AQUI')
WEBPUSH_CONTACT_EMAIL = os.getenv('WEBPUSH_CONTACT_EMAIL', 'tu_email@ejemplo.com')

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}

# ==================== MONGODB CONFIGURATION ====================
MONGODB_URI = os.getenv('MONGODB_URI', 'mongodb://localhost:27017/')
MONGODB_NAME = os.getenv('MONGODB_NAME', 'miniamigixv_db')

# Conectar a MongoDB (opcional)
try:
    from mongoengine import connect
    connect(db=MONGODB_NAME, host=MONGODB_URI, alias='default')
    print(f"✓ Conectado a MongoDB: {MONGODB_NAME}")
except ImportError:
    print(f"⚠ mongoengine no está instalado. MongoDB no estará disponible.")
except Exception as e:
    print(f"✗ Error al conectar a MongoDB: {str(e)}")

# Configuración de MongoEngine
MONGOENGINE_USER_DOCUMENT = 'mongoengine.django.auth.User'
