# Generated by Django 6.0.6 on 2026-06-11 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cancion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(choices=[('noticias', '📰 Noticias'), ('consejos', '💡 Consejos'), ('tutorial', '🎯 Tutorial'), ('personal', '📝 Personal'), ('anuncios', '🚀 Anuncios')], default='personal', max_length=50)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('publicado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicación de Blog',
                'verbose_name_plural': 'Publicaciones de Blog',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
