# Generated by Django 5.1.15 on 2026-06-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_publicacionblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacionblog',
            options={'ordering': ['-fijado', '-fecha_publicacion'], 'verbose_name': 'Publicación de Blog', 'verbose_name_plural': 'Publicaciones de Blog'},
        ),
        migrations.AddField(
            model_name='publicacionblog',
            name='es_oficial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicacionblog',
            name='fijado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicacionblog',
            name='visible_para_todos',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publicacionblog',
            name='categoria',
            field=models.CharField(choices=[('noticias', '📰 Noticias'), ('consejos', '💡 Consejos'), ('tutorial', '🎯 Tutorial'), ('personal', '📝 Personal'), ('anuncios', '🚀 Anuncios'), ('mantenimiento', '⚙️ Mantenimiento'), ('actualizaciones', '🔄 Actualizaciones'), ('avisos_urgentes', '⚠️ Avisos Urgentes')], default='personal', max_length=50),
        ),
    ]
