# Generated by Django 6.0.6 on 2026-06-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_game_achievement_score_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
    ]
