# Generated by Django 6.0.6 on 2026-06-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cancion_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='letra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancion',
            name='letra_sincronizada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
