# Generated by Django 6.0.6 on 2026-06-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_cancion_letra_cancion_letra_sincronizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacionEntretenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('peliculas', 'Películas'), ('series', 'Series'), ('libros', 'Libros'), ('teatro', 'Teatro')], max_length=50)),
                ('datos', models.JSONField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recomendación de Entretenimiento',
                'verbose_name_plural': 'Recomendaciones de Entretenimiento',
            },
        ),
    ]
