# Generated by Django 6.0.6 on 2026-06-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_recomendacionentretenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionblog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
