# Generated by Django 6.0.6 on 2026-06-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_publicacionblog_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajechat',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
