# Generated by Django 6.0.6 on 2026-06-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_mensajechat_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacionblog',
            name='categoria_dinamica',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='padre',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='publicacionblog',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='PublicacionBlog',
        ),
    ]
