# Generated by Django 6.0.6 on 2026-07-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_blog_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionchat',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='tipo',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('memoria', 'Memoria'), ('matematicas', 'Matemáticas'), ('palabras', 'Palabras'), ('logica', 'Lógica'), ('reflejos', 'Reflejos'), ('fidget', 'Fidget'), ('respiracion', 'Respiración'), ('snake', 'Snake'), ('tres_en_raya', '3 en Raya'), ('ajedrez', 'Ajedrez')], default='quiz', max_length=50),
        ),
    ]
