# Generated by Django 6.0.6 on 2026-07-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_conversacionchat_favorito_alter_game_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='categoria',
            field=models.CharField(choices=[('inteligencia', 'Inteligencia'), ('velocidad', 'Velocidad'), ('precision', 'Precisión'), ('estrategia', 'Estrategia'), ('relax', 'Relax')], default='inteligencia', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='icono',
            field=models.CharField(default='🎮', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='tiempo_estimado',
            field=models.CharField(default='5 min', max_length=50),
        ),
    ]
