# Generated by Django 6.0.6 on 2026-07-24 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_game_categoria_game_icono_game_tiempo_estimado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcadeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('monedas', models.IntegerField(default=0)),
                ('partidas_ganadas', models.IntegerField(default=0)),
                ('racha_dias', models.IntegerField(default=0)),
                ('ultima_partida', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arcade_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Arcade',
                'verbose_name_plural': 'Perfiles Arcade',
            },
        ),
    ]
