# Generated by Django 6.0.5 on 2026-05-26 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=50)),
                ('contenido', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('lectura_min', models.PositiveIntegerField(default=1)),
                ('post_type', models.CharField(choices=[('personal', 'Personal'), ('admin', 'Admin')], default='personal', max_length=10)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
