# Generated by Django 6.0.6 on 2026-06-24 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(default='ES', max_length=100)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('temperatura', models.FloatField(help_text='Temperatura en Celsius')),
                ('sensacion_termica', models.FloatField(blank=True, null=True)),
                ('humedad', models.IntegerField(blank=True, null=True)),
                ('presion', models.IntegerField(blank=True, null=True)),
                ('viento_velocidad', models.FloatField(blank=True, null=True)),
                ('viento_direccion', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('pronostico', models.JSONField(default=dict, help_text='Pronóstico para los próximos días')),
                ('fecha_consulta', models.DateTimeField(auto_now=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caché de Clima',
                'verbose_name_plural': 'Cachés de Clima',
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
