# Generated by Django 6.0.6 on 2026-07-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathercache',
            name='icono',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
