# Generated by Django 6.0.6 on 2026-07-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0002_alter_weathercache_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathercache',
            name='amanecer',
            field=models.TimeField(blank=True, help_text='Hora de amanecer', null=True),
        ),
        migrations.AddField(
            model_name='weathercache',
            name='atardecer',
            field=models.TimeField(blank=True, help_text='Hora de atardecer', null=True),
        ),
        migrations.AddField(
            model_name='weathercache',
            name='probabilidad_lluvia',
            field=models.IntegerField(blank=True, help_text='Probabilidad de lluvia %', null=True),
        ),
        migrations.AddField(
            model_name='weathercache',
            name='temp_max',
            field=models.FloatField(blank=True, help_text='Temperatura máxima del día', null=True),
        ),
        migrations.AddField(
            model_name='weathercache',
            name='temp_min',
            field=models.FloatField(blank=True, help_text='Temperatura mínima del día', null=True),
        ),
        migrations.AddField(
            model_name='weathercache',
            name='uv_index',
            field=models.IntegerField(blank=True, help_text='Índice UV', null=True),
        ),
        migrations.AddField(
            model_name='weathercache',
            name='visibilidad',
            field=models.FloatField(blank=True, help_text='Visibilidad en km', null=True),
        ),
    ]
