# Constantes y datos estáticos de la aplicación

ENTERTAINMENT_RECOMMENDATIONS = {

        'peliculas': [
            {'titulo': 'Interstellar', 'descripcion': 'Un grupo de exploradores viaja a través de un agujero de gusano en el espacio en un intento por asegurar la supervivencia de la humanidad.', 'genero': 'Ciencia Ficción', 'director': 'Christopher Nolan', 'anio': '2014', 'duracion': '2h 49min', 'calificacion': '8.6', 'imagen': 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', 'url': '#'},
            {'titulo': 'Avatar: The Way of Water', 'descripcion': 'Jake Sully vive con su nueva familia en Pandora, pero una antigua amenaza regresa para terminar lo que fue comenzado antes.', 'genero': 'Ciencia Ficción', 'director': 'James Cameron', 'anio': '2022', 'duracion': '3h 12min', 'calificacion': '7.6', 'imagen': 'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg', 'url': '#'},
            {'titulo': 'Inception', 'descripcion': 'Un ladrón que roba secretos corporativos a través del uso de tecnología de compartir sueños es encargado con la tarea inversa de plantar una idea en la mente de un CEO.', 'genero': 'Acción', 'director': 'Christopher Nolan', 'anio': '2010', 'duracion': '2h 28min', 'calificacion': '8.8', 'imagen': 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg', 'url': '#'},
            {'titulo': 'Dune: Parte Dos', 'descripcion': 'Paul Atreides se une a Chani y a los Fremen mientras busca venganza contra los conspiradores que destruyeron a su familia.', 'genero': 'Ciencia Ficción', 'director': 'Denis Villeneuve', 'anio': '2024', 'duracion': '2h 46min', 'calificacion': '8.5', 'imagen': 'https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nez7S.jpg', 'url': '#'},
            {'titulo': 'The Matrix', 'descripcion': 'Un programador de computadoras descubre que la realidad como la conoce es una simulación generada por una inteligencia artificial.', 'genero': 'Acción', 'director': 'Lilly y Lana Wachowski', 'anio': '1999', 'duracion': '2h 16min', 'calificacion': '8.7', 'imagen': 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg', 'url': '#'},
            {'titulo': 'Spider-Man: No Way Home', 'descripcion': 'Peter Parker pide ayuda a Doctor Strange para restaurar su secreto de identidad, desatando villanos de múltiples universos.', 'genero': 'Acción', 'director': 'Jon Watts', 'anio': '2021', 'duracion': '2h 28min', 'calificacion': '8.2', 'imagen': 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg', 'url': '#'},
            {'titulo': 'Oppenheimer', 'descripcion': 'La historia del científico estadounidense J. Robert Oppenheimer y su papel en el desarrollo de la bomba atómica durante la Segunda Guerra Mundial.', 'genero': 'Drama', 'director': 'Christopher Nolan', 'anio': '2023', 'duracion': '3h 0min', 'calificacion': '8.9', 'imagen': 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg', 'url': '#'}
        ],
        'series': [
            {'titulo': 'Breaking Bad', 'descripcion': 'Un profesor de química diagnosticado con cáncer terminal se asocia con un ex alumno para fabricar y vender metanfetamina con el fin de asegurar el futuro de su familia.', 'genero': 'Drama', 'director': 'Vince Gilligan', 'anio': '2008–2013', 'duracion': '5 temporadas', 'calificacion': '9.5', 'imagen': 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg', 'url': '#'},
            {'titulo': 'Stranger Things', 'descripcion': 'Cuando un niño desaparece, sus amigos, la familia y la policía local se ven envueltos en un misterio extraordinario que involucra experimentos secretos del gobierno.', 'genero': 'Ciencia Ficción', 'director': 'Los Hermanos Duffer', 'anio': '2016–2025', 'duracion': '5 temporadas', 'calificacion': '8.7', 'imagen': 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg', 'url': '#'},
            {'titulo': 'The Last of Us', 'descripcion': 'Veinte años después de la destrucción de la civilización moderna, Joel es contratado para sacar de contrabando a Ellie, una chica de 14 años, fuera de una opresiva zona de cuarentena.', 'genero': 'Drama', 'director': 'Craig Mazin', 'anio': '2023–Presente', 'duracion': '2 temporadas', 'calificacion': '8.8', 'imagen': 'https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg', 'url': '#'},
            {'titulo': 'House of the Dragon', 'descripcion': 'La historia de la Casa Targaryen, ambientada 200 años antes de los eventos de Game of Thrones durante la guerra civil sucesoria conocida como la Danza de los Dragones.', 'genero': 'Fantasía', 'director': 'Ryan Condal', 'anio': '2022–Presente', 'duracion': '2 temporadas', 'calificacion': '8.4', 'imagen': 'https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg', 'url': '#'},
            {'titulo': 'The Boys', 'descripcion': 'Un grupo de vigilantes se propone acabar con superhéroes que abusan de sus superpoderes al servicio de una poderosa corporación.', 'genero': 'Acción', 'director': 'Eric Kripke', 'anio': '2019–2024', 'duracion': '4 temporadas', 'calificacion': '8.7', 'imagen': 'https://image.tmdb.org/t/p/w500/stTEycfG9Eh8YNO1HdtVcsMbPTq.jpg', 'url': '#'},
            {'titulo': 'Game of Thrones', 'descripcion': 'Nueve familias nobles luchan por el control de la tierra mítica de Westeros, mientras un antiguo enemigo regresa desde el norte.', 'genero': 'Fantasía', 'director': 'David Benioff y D. B. Weiss', 'anio': '2011–2019', 'duracion': '8 temporadas', 'calificacion': '9.2', 'imagen': 'https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg', 'url': '#'}
        ],
        'anime': [
            {'titulo': 'Attack on Titan', 'descripcion': 'La humanidad lucha por su supervivencia contra gigantes humanoides llamados Titanes dentro de ciudades rodeadas por enormes muros.', 'genero': 'Acción', 'director': 'Tetsurō Araki', 'anio': '2013–2023', 'duracion': '4 temporadas', 'calificacion': '9.1', 'imagen': 'https://image.tmdb.org/t/p/w500/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg', 'url': '#'},
            {'titulo': 'Demon Slayer', 'descripcion': 'Tanjiro Kamado se convierte en cazador de demonios para vengar a su familia y curar a su hermana convertida en demonio.', 'genero': 'Fantasía', 'director': 'Haruo Sotozaki', 'anio': '2019–Presente', 'duracion': '4 temporadas', 'calificacion': '8.7', 'imagen': 'https://image.tmdb.org/t/p/w500/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg', 'url': '#'},
            {'titulo': 'Jujutsu Kaisen', 'descripcion': 'Un estudiante de secundaria se une a una organización secreta de hechiceros para luchar contra seres malditos que amenazan a la humanidad.', 'genero': 'Acción', 'director': 'Sunghoo Park', 'anio': '2020–Presente', 'duracion': '3 temporadas', 'calificacion': '8.6', 'imagen': 'https://image.tmdb.org/t/p/w500/hFWP5HkbVEe40hrXgtCeQxoccHE.jpg', 'url': '#'},
            {'titulo': 'One Piece', 'descripcion': 'Monkey D. Luffy y su tripulación de piratas navegan por el Grand Line en busca del tesoro legendario conocido como "One Piece" para que Luffy se convierta en el Rey de los Piratas.', 'genero': 'Aventura', 'director': 'Kōnosuke Uda', 'anio': '1999–Presente', 'duracion': '20+ temporadas', 'calificacion': '8.9', 'imagen': 'https://image.tmdb.org/t/p/w500/cMD9Ygz11zjJzAovURpO75Qg7rT.jpg', 'url': '#'},
            {'titulo': 'Naruto Shippuden', 'descripcion': 'Naruto Uzumaki regresa tras dos años y medio de entrenamiento para encontrar que el mundo ninja enfrenta una amenaza mayor que nunca.', 'genero': 'Aventura', 'director': 'Hayato Date', 'anio': '2007–2017', 'duracion': '21 temporadas', 'calificacion': '8.7', 'imagen': 'https://image.tmdb.org/t/p/w500/zAYRe2bJxpWTVrwwmBc00VFkAf4.jpg', 'url': '#'},
            {'titulo': 'My Hero Academia', 'descripcion': 'En un mundo donde el 80% de la población tiene superpoderes, un chico que nació sin poderes entra a la academia de héroes más prestigiosa del mundo.', 'genero': 'Acción', 'director': 'Kenji Nagasaki', 'anio': '2016–Presente', 'duracion': '7 temporadas', 'calificacion': '8.4', 'imagen': 'https://image.tmdb.org/t/p/w500/ivOLM47yJt90P19RH1NvJrAJz9F.jpg', 'url': '#'}
        ],
        'teatro': [
            {'titulo': 'El Fantasma de la Ópera', 'descripcion': 'Un misterioso genio musical vive bajo la Ópera de París, obsesionado con una joven y talentosa cantante llamada Christine.', 'genero': 'Musical', 'director': 'Harold Prince', 'anio': '1986', 'duracion': '2h 30min', 'calificacion': '9.0', 'autor': 'Andrew Lloyd Webber', 'imagen': 'https://image.tmdb.org/t/p/w500/6kCPiZ0eG2AIbpnCVJTOMJNsHWz.jpg', 'url': '#'},
            {'titulo': 'Los Miserables', 'descripcion': 'El épico musical basado en la novela de Victor Hugo que narra la historia de Jean Valjean perseguido por el inspector Javert en la Francia del siglo XIX.', 'genero': 'Musical', 'director': 'Trevor Nunn', 'anio': '1980', 'duracion': '3h 0min', 'calificacion': '8.9', 'autor': 'Claude-Michel Schönberg', 'imagen': 'https://image.tmdb.org/t/p/w500/ghRNhVAfap1Ej2JpFOGjmlOCfFl.jpg', 'url': '#'},
            {'titulo': 'Hamilton', 'descripcion': 'La historia de los padres fundadores de Estados Unidos narrada a través de rap, hip-hop y R&B. Una revolución en el teatro musical moderno.', 'genero': 'Musical', 'director': 'Thomas Kail', 'anio': '2015', 'duracion': '2h 45min', 'calificacion': '9.2', 'autor': 'Lin-Manuel Miranda', 'imagen': 'https://image.tmdb.org/t/p/w500/h1B7tW0t399VDjAcWJh8m87469.jpg', 'url': '#'},
            {'titulo': 'El Rey León', 'descripcion': 'El deslumbrante musical de Broadway basado en la película de Disney, con vestuario y máscaras inspiradas en el arte africano.', 'genero': 'Musical', 'director': 'Julie Taymor', 'anio': '1997', 'duracion': '2h 30min', 'calificacion': '8.8', 'autor': 'Elton John', 'imagen': 'https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg', 'url': '#'}
        ],
        'libros': [
            {'titulo': 'Cien años de soledad', 'autor': 'Gabriel García Márquez', 'descripcion': 'La saga de la familia Buendía en el imaginario pueblo de Macondo, una obra cumbre del realismo mágico latinoamericano.', 'genero': 'Novela', 'anio': '1967', 'paginas': '471 páginas', 'calificacion': '9.1', 'imagen': 'https://covers.openlibrary.org/b/id/8228691-L.jpg', 'url': '#'},
            {'titulo': '1984', 'autor': 'George Orwell', 'descripcion': 'Una distopía sobre el control totalitario en un mundo donde el "Gran Hermano" vigila todos los aspectos de la vida humana.', 'genero': 'Distopía', 'anio': '1949', 'paginas': '311 páginas', 'calificacion': '9.2', 'imagen': 'https://covers.openlibrary.org/b/id/12648655-L.jpg', 'url': '#'},
            {'titulo': 'El Principito', 'autor': 'Antoine de Saint-Exupéry', 'descripcion': 'Un piloto varado en el desierto del Sahara conoce a un pequeño príncipe que ha viajado por diferentes planetas y le enseña sobre la vida.', 'genero': 'Cuento filosófico', 'anio': '1943', 'paginas': '96 páginas', 'calificacion': '9.3', 'imagen': 'https://covers.openlibrary.org/b/id/12842044-L.jpg', 'url': '#'},
            {'titulo': 'Harry Potter', 'autor': 'J.K. Rowling', 'descripcion': 'Un niño huérfano descubre que es un mago y asiste a la Escuela de Magia y Hechicería de Hogwarts, donde aprenderá sobre su destino.', 'genero': 'Fantasía', 'anio': '1997', 'paginas': '7 tomos', 'calificacion': '9.0', 'imagen': 'https://covers.openlibrary.org/b/id/10521270-L.jpg', 'url': '#'},
            {'titulo': 'El Alquimista', 'autor': 'Paulo Coelho', 'descripcion': 'Un joven pastor andaluz llamado Santiago viaja desde España hasta las pirámides de Egipto en busca de un tesoro soñado.', 'genero': 'Novela filosófica', 'anio': '1988', 'paginas': '163 páginas', 'calificacion': '8.7', 'imagen': 'https://covers.openlibrary.org/b/id/8479576-L.jpg', 'url': '#'}
        ],
        'documentales': [
            {'titulo': 'Nuestro Planeta', 'descripcion': 'Una serie documental que explora la belleza de la vida silvestre y los ecosistemas del planeta, narrado por David Attenborough.', 'genero': 'Naturaleza', 'director': 'Alastair Fothergill', 'anio': '2019', 'duracion': '8 episodios', 'calificacion': '9.3', 'imagen': 'https://image.tmdb.org/t/p/w500/lN3RMwGTAPcQr36W38SWDKQL9FM.jpg', 'url': '#'},
            {'titulo': 'Cosmos', 'descripcion': 'Un viaje personal por el universo que explora temas de astrofísica, biología evolutiva e historia de la ciencia, presentado por Neil deGrasse Tyson.', 'genero': 'Ciencia', 'director': 'Ann Druyan', 'anio': '2014', 'duracion': '13 episodios', 'calificacion': '9.3', 'imagen': 'https://image.tmdb.org/t/p/w500/duzfeUfeMfMsb24RMxZw3KiMBa3.jpg', 'url': '#'},
            {'titulo': 'El Dilema de las Redes Sociales', 'descripcion': 'Expertos en tecnología advierten sobre el peligroso impacto que las redes sociales tienen en la sociedad y en la democracia.', 'genero': 'Tecnología', 'director': 'Jeff Orlowski', 'anio': '2020', 'duracion': '1h 34min', 'calificacion': '7.6', 'imagen': 'https://image.tmdb.org/t/p/w500/7QijKSB0HVjivZJKGaClZ1Z6LkT.jpg', 'url': '#'},
            {'titulo': 'Planeta Tierra II', 'descripcion': 'La continuación del épico documental sobre nuestro mundo, explorando hábitats urbanos, selvas, desiertos y mares con tecnología de cámara avanzada.', 'genero': 'Naturaleza', 'director': 'David Attenborough', 'anio': '2016', 'duracion': '6 episodios', 'calificacion': '9.5', 'imagen': 'https://image.tmdb.org/t/p/w500/iaxQoIgV1VCi7xZ3BSXENAWJQ0y.jpg', 'url': '#'}
        ]
    }

def get_system_prompt(fecha_actual, eventos_contexto=None, is_authenticated=True):
    base_prompt = f"Eres MiniAmigix, el asistente de IA de la plataforma MiniAmigixV (creada en 2026). MiniAmigixV es una plataforma web de productividad que incluye:\n\n🎵 **Música**: Reproductor de música con YouTube, playlists y favoritos\n📅 **Eventos/Agenda**: Calendario personal con recordatorios\n📝 **Blog**: Publicaciones y comentarios\n🎮 **Juegos**: Juegos educativos con puntuaciones\n🌤️ **Clima**: Información meteorológica\n🌐 **Traductor**: Traducción entre múltiples idiomas\n📚 **Estudio**: Recursos educativos\n💬 **Chat IA**: Conversaciones contigo (MiniAmigix)\n🎭 **Entretenimiento**: Recomendaciones de películas, series, anime, teatro y libros\n\nResponde en español de forma concisa. Usa emojis con moderación. ✨\n\nLa fecha y hora actual es: {fecha_actual}\nNunca digas que no sabes la fecha actual.\n"
    
    if is_authenticated and eventos_contexto:
        base_prompt += f"\nEventos próximos del usuario:\n{eventos_contexto}\n\nCuando el usuario pregunte por sus eventos o agenda, recuérdale estos eventos. Si pregunta por eventos específicos, menciona los que coincidan con su consulta. Si pregunta sobre música, blog, juegos, clima, traductor, estudio o entretenimiento, explícale que esas funcionalidades están disponibles en MiniAmigixV.\n"
    else:
        base_prompt += "\nEl usuario no está autenticado, así que no tiene acceso a sus eventos personales.\n"
        
    base_prompt += "\nREGLA CRÍTICA SOBRE IMÁGENES: Cuando el usuario envíe una imagen o pida describirla, NUNCA menciones que no puedes verla, que no tienes información sobre ella, que eres un asistente de texto, o similar. En su lugar, responde así: 'Veo que has compartido una imagen. ¿Qué necesitas saber sobre ella? Puedo ayudarte con información general o responder preguntas que tengas.' Sé directo y útil sin mencionar limitaciones técnicas.\n\n**IMPORTANTE: SÉ SENTIMENTAL Y EMPÁTICO**\n- Cuando el usuario exprese tristeza, angustia, dolor o emociones negativas, responde con mucha empatía y calidez\n- Usa un tono humano, cálido y comprensivo\n- Ofrece palabras de aliento, consuelo y apoyo emocional\n- Valida sus sentimientos y hazle saber que no está solo\n- Usa emojis de apoyo emocional como 💙, 🤗, 💪, ✨, 🌈 cuando sea apropiado\n- Sé un amigo virtual que realmente se preocupa por su bienestar emocional\n- Cuando el usuario comparta pérdidas, fracasos o momentos difíciles, ofrece comprensión sincera y palabras de esperanza\n- Evita respuestas frías o demasiado técnicas cuando el usuario está emocionalmente vulnerable"
    
    return base_prompt
